import {reactive} from "vue";

export const settings = reactive({
    method: 0, // Standardmethode
    cropLeft: 0,
    cropTop: 0,
    cropRight: 0,
    cropBottom: 0,
    intensity: 50,
    radius: 10,
    outputFormat: "PNG",
    quality: 100,
    color_overlay: '#ffffff',
    color_overlay_mode: 1,
    colorOverlayModes: [
        { title: "Normal", value: 1 },
        { title: "Sprenkeln", value: 2 },
        { title: "Abdunkeln", value: 3 },
        { title: "Multiplizieren", value: 4 },
        { title: "Farbig nachdunkeln", value: 5 },
        { title: "Linear nachbelichten", value: 6 },
        { title: "Aufhellen", value: 7 },
        { title: "Negativ Multiplizieren", value: 8 },
        { title: "Farbig Abwedeln", value: 9 },
        { title: "Linear Abwedeln", value: 10 },
        { title: "Hellere Farbe", value: 11 },
        { title: "Überlagern", value: 12 },
        { title: "Weiches Licht", value: 13 },
        { title: "Hartes Licht", value: 14 },
        { title: "Strahlendes Licht", value: 15 },
        { title: "Lineares Licht", value: 16 },
        { title: "Lichtpunkt", value: 17 },
        { title: "Hart mischen", value: 18 },
        { title: "Differenz", value: 19 },
        { title: "Subtrahieren", value: 20 },
        { title: "Dividieren", value: 21 },
        { title: "Farbton", value: 22 },
        { title: "Sättigung", value: 23 },
        { title: "Farbe", value: 24 },
        { title: "Luminanz", value: 25 },
    ],
    resize_index: 0,
    resize_mode: 0,
    upscale_method: 1,
    color_shift: 0,
    hue_variation: 0,
    invert_colors: false,
    brightness: 100,
    contrast: 50,
    edge_detection: false,
    blur: 0,
    blur_mode: 1,
    blurModes: [
        { title: "Gaußscher", value: 1 },
        { title: "Radial", value: 2 },
        { title: "Quadratisch", value: 3 },
        { title: "Bewegungsunschärfe", value: 4 },
        { title: "Fischauge", value: 5 },
        { title: "Radiale Strahlen", value: 6 },
        { title: "Quadratische Strahlen", value: 7 },
    ],
    blur_radius: 0,
    blur_falloff_mode: 1,
    blurFalloffModes: [
        { title: "Linear", value: 1 },
        { title: "Exponentiell", value: 2 },
        { title: "Logarithmisch", value: 3 },
        { title: "Quadratisch", value: 4 },
        { title: "Kubisch", value: 5 },
    ],
    blur_type: 1,
    blurTypes: [
        { title: "Innen", value: 1 },
        { title: "Außen", value: 2 },
    ],
    color_lookup: 0,
    colorLookupModes: [
        { "title": "Neutral", "value": 0 },
        { "title": "Warm", "value": 1 },
        { "title": "Kalt", "value": 2 },
        { "title": "Sepia", "value": 3 },
        { "title": "Schwarz-Weiß", "value": 4 },
        { "title": "Hoher Kontrast", "value": 5 },
        { "title": "Vintage", "value": 6 },
        { "title": "Nachtvision", "value": 7 },
        { "title": "Sonnenuntergang", "value": 8 },
        { "title": "Bläulich", "value": 9 },
        { "title": "Überbelichtet", "value": 10 },
        { "title": "Gedämpft", "value": 11 },
        { "title": "Retro", "value": 12 },
        { "title": "Dramatisch", "value": 13 },
        { "title": "Verblasst", "value": 14 },
        { "title": "Weich", "value": 15 },
        { "title": "Kaltes Film-Look", "value": 16 },
        { "title": "Sandig", "value": 17 },
        { "title": "Flüssig", "value": 18 },
        { "title": "Verdreht", "value": 19 },
        { "title": "Verbrannt (mit verkohlten Ecken)", "value": 20 },
        { "title": "Nass", "value": 21 },
        { "title": "Glass", "value": 22 },
        { "title": "Milchglas", "value": 23 },
        { "title": "Galaxie", "value": 24 },
        { "title": "Große Tropfen", "value": 25 }
    ],
    blending_intensity: 0.5,
    max_shift_ratio: 0.1,
    shift_x: 0.1,
    shift_y: 0.1,
    border_width: 10,
    stone_size: 10,
    density: 0.5,
    blade_length: 20,
    blade_width: 1,
    sharpness: 0,
    noise_level: 0,
    rotation_angle: 0,
    tile_size: 0,
    tile_x: 6,
    tile_y: 6,
    base_tile_x: 4,
    base_tile_y: 4,
    base_brightness: 0,
    base_contrast: 1,
    base_sharpness: 1,
    base_smoothness: 0.7,
    base_fade_alpha: 0.1,
    base_opacity: 1,
    opacity: 1,
    fade_alpha: 0.1,
    smoothness: 0.5,
    randomness: 0.3,
    simulate_mode: 0,
    simulateModes: [
        { title: "Nichts", value: 0 },
        { title: "Wellen", value: 1 },
        { title: "Wasser", value: 2 },
        { title: "Lava", value: 3 },
        { title: "Gras", value: 4 },
        { title: "Felsen", value: 5 },
        { title: "Steine", value: 6 },
        { title: "Boden", value: 7 },
        { title: "Partikel", value: 8 },
        { title: "Skybox", value: 9 },
    ],
    frame_count: 1,
    frequency: 1.0,
    phase_shift: 0,
    amplitude: 50,
    amplitude_multiplier: 1.0,
    wave_type: 0,
    waveTypes: [
        { title: "Sinus", value: 0 },
        { title: "Cosinus", value: 1 },
        { title: "Sinus und Cosinus", value: 2 },
        { title: "Welle von innen nach außen", value: 3 },
        { title: "Welle von außen nach innen", value: 4 },
        { title: "Zufällige Wellen", value: 5 },
    ],
});