# generate_with_import_rewrite.py
from __future__ import annotations
import importlib.util
import re
from pathlib import Path
from typing import Any, Mapping, Optional, Dict, Tuple, List
from core.compiler.main import Compiler

def _log(msg: str, src: str = "GEN", lvl: str = "INFO", icon: str = "🧩"):
    print(f"[{src}] {icon} {lvl}: {msg}")

class Generate:
    """
    Kopiert view/controller/model Dateien nach ./generated/
    - rewritet Imports
    - verwendet Compiler.compile(...) für Templates (Compiler liefert string zurück)
    - init_setup() initialisiert und führt die Generierung basierend auf self.config aus
    """
    def __init__(self, config: Mapping[str, Any], base_dir: str = "."):
        self.config = config
        self.base_dir = Path(base_dir).resolve()
        self.gen_root = self.base_dir / "generated"
        self.dirs = {
            "view": self.gen_root / "view",
            "controller": self.gen_root / "controller",
            "model": self.gen_root / "model",
        }
        self.compiler = Compiler(config)
        # Liste der geschriebenen Dateien (wird von _write gepflegt)
        self._written: List[Path] = []

    # -------------------
    # FS helpers
    # -------------------
    def _ensure_dir(self, path: Path):
        path.mkdir(parents=True, exist_ok=True)

    def _ensure_packages(self):
        self._ensure_dir(self.gen_root)
        for p in (
            "",
            "view",
            "controller",
            "model",
            "view/base",
            "controller/base",
            "model/base",
        ):
            pkg = self.gen_root / p
            self._ensure_dir(pkg)
            init = pkg / "__init__.py"
            if not init.exists():
                init.write_text("# autogenerated package\n", encoding="utf-8")

    def _is_source_file(self, module_path: str) -> Optional[Path]:
        try:
            spec = importlib.util.find_spec(module_path)
            if spec and spec.origin and spec.origin != "built-in":
                p = Path(spec.origin)
                if p.is_file():
                    return p
        except Exception:
            pass
        return None

    def _read_source(self, module_path: str) -> Optional[str]:
        p = self._is_source_file(module_path)
        if p:
            try:
                return p.read_text(encoding="utf-8")
            except Exception:
                return None
        return None

    # -------------------
    # Import rewrite
    # -------------------
    def _rewrite_imports_to_generated(self, src: str) -> str:
        def repl_from(match):
            mod = match.group(1)
            if mod.startswith("generated."):
                return match.group(0)
            return f"from generated.{mod} import"

        def repl_import(match):
            mod = match.group(1)
            if mod.startswith("generated."):
                return match.group(0)
            return f"import generated.{mod}"

        src = re.sub(r"\bfrom\s+((?:view|controller|model)(?:\.[0-9A-Za-z_\.]+)?)\s+import\b", repl_from, src)
        src = re.sub(r"\bimport\s+((?:view|controller|model)(?:\.[0-9A-Za-z_\.]+)?)\b", repl_import, src)
        return src

    # -------------------
    # Helpers: prüfen, ob Pfad unter generated liegt
    # -------------------
    def _is_under_generated(self, path: Path) -> bool:
        """
        True wenn path innerhalb self.gen_root liegt (oder gleich dem gen_root).
        """
        try:
            p = path.resolve()
            # p == gen_root OR gen_root in p.parents
            return p == self.gen_root or self.gen_root in p.parents
        except Exception:
            return False

    # -------------------
    # Write helper (Generate schreibt) — schützt externe Dateien
    # -------------------
    def _write(self, path: Path, content: str, overwrite: bool):
        path = path.resolve()

        # Schütze Schreibziel außerhalb von generated/
        if not self._is_under_generated(path):
            _log(f"Protect non-generated file (will not write): {path}", lvl="WARNING")
            return

        # existierende Datei unter generated: nur überschreiben wenn overwrite True
        if path.exists() and not overwrite:
            _log(f"Skip existing (overwrite=False): {path}", lvl="DEBUG")
            return

        # jetzt schreiben (neue Datei oder overwrite=True)
        self._ensure_dir(path.parent)
        path.write_text(content, encoding="utf-8")

        # protokolliere geschriebene Datei
        self._written.append(path)
        _log(f"Wrote: {path}", lvl="DEBUG")

    # -------------------
    # Copy base files
    # -------------------
    def _copy_base_files(self, overwrite: bool):
        bases = [
            ("view.base.main", self.dirs["view"] / "base" / "main.py"),
            ("controller.base.main", self.dirs["controller"] / "base" / "main.py"),
            ("model.base.main", self.dirs["model"] / "base" / "main.py"),
        ]
        for module_path, target_path in bases:
            src = self._read_source(module_path)
            if src:
                try:
                    src_mod = self._rewrite_imports_to_generated(src)
                    self._write(target_path, src_mod, overwrite)
                except Exception as e:
                    _log(f"Failed to copy base {module_path}: {e}", lvl="WARN")
            else:
                # minimal fallback
                content = ""
                if module_path.startswith("view"):
                    content = "class BaseView:\n    def __init__(self, *a, **k):\n        pass\n"
                elif module_path.startswith("controller"):
                    content = "class BaseController:\n    def __init__(self, *a, **k):\n        pass\n"
                else:
                    content = "class BaseModel:\n    def __init__(self, *a, **k):\n        pass\n"
                self._write(target_path, content, overwrite)

    # -------------------
    # Detect blueprint var name in source like: router_x = Blueprint(...)
    # -------------------
    def _detect_blueprint_var(self, src_text: Optional[str]) -> Optional[str]:
        if not src_text:
            return None
        m = re.search(r"^(\w+)\s*=\s*Blueprint\s*\(", src_text, flags=re.MULTILINE)
        return m.group(1) if m else None

    # -------------------
    # init_setup
    # -------------------
    def init_setup(self, overwrite: bool = False, overwrite_base: bool = False) -> Dict[str, Any]:
        """
        Initialisiert die generated/ Struktur, kopiert Base-Files und führt die Generierung
        für alle Router-Einträge in self.config aus.

        Args:
            overwrite: überschreibe bereits generierte Dateien (default: False)
            overwrite_base: überschreibe Base-Files beim Kopieren (default: False)

        Returns:
            dict mit Zusammenfassung: {
                "success": bool,
                "generated_count": int,
                "generated_files": [str,...],
                "errors": [str,...]
            }
        """
        summary: Dict[str, Any] = {"success": True, "generated_count": 0, "generated_files": [], "errors": []}
        _log("init_setup: Initialisiere generierte Struktur...", lvl="INFO")

        try:
            # packages + base files (base overwrite controlled separately)
            self._ensure_packages()
            self._copy_base_files(overwrite_base)
            for d in self.dirs.values():
                self._ensure_dir(d)
                _log(f"Verzeichnis bereitgestellt: {d}", lvl="DEBUG")

            # clear written-log for fresh run
            self._written = []

            # main generation
            _log("init_setup: Starte Generierung aus config...", lvl="INFO")
            try:
                self.generate_from_config(self.config, overwrite=overwrite)
            except Exception as e:
                # generate_from_config intern loggt tracebacks, wir fangen dennoch um summary zu füllen
                summary["success"] = False
                summary["errors"].append(f"generate_from_config failed: {e}")

            # fill summary from _written
            summary["generated_files"] = [str(p) for p in self._written]
            summary["generated_count"] = len(self._written)
            _log(f"init_setup: Fertig. Dateien geschrieben: {summary['generated_count']}", lvl="INFO")

        except Exception as e:
            import traceback
            tb = traceback.format_exc()
            _log(f"init_setup Fehler: {e}\n{tb}", lvl="ERROR")
            summary["success"] = False
            summary["errors"].append(str(e))

        return summary

    # -------------------
    # Main generation (Generate ruft Compiler.compile und schreibt Ergebnis)
    # -------------------
    def generate_from_config(self, config: Mapping[str, Any], overwrite: bool = False) -> bool:
        self._ensure_packages()
        self._copy_base_files(overwrite)
        for d in self.dirs.values():
            self._ensure_dir(d)

        for entry in config.get("router", []):
            try:
                blueprint = entry.get("blueprint", "")
                view_mod_cfg = entry.get("view_module")
                ctrl_mod_cfg = entry.get("controller")
                mdl_mod_cfg = entry.get("model")
                url_prefix = entry.get("url", "/" + blueprint.replace("router_", "")) if blueprint else "/"
                strict_val = entry.get("strict_slashes", None)
                if strict_val is not None:
                    strict_val = bool(strict_val)

                generated_decl = f"# GENERATED_URL_PREFIX = {url_prefix!r}\n# GENERATED_STRICT_SLASHES = {strict_val!r}\n\n"

                # ---------- VIEW ----------
                if view_mod_cfg:
                    view_basename = view_mod_cfg.split(".")[-1]
                    src = self._read_source(view_mod_cfg)
                    view_path = self.dirs["view"] / f"{view_basename}.py"
                    if src:
                        blueprint_var = self._detect_blueprint_var(src)
                        # compile if template markers found
                        if ("{{" in src) or ("{%" in src):
                            try:
                                compiled = self.compiler.compile(src, {}, blueprint_var, entry)
                            except Exception as e:
                                _log(f"Template compilation error for view {view_mod_cfg}: {e}", lvl="ERROR")
                                # don't raise — continue with other entries
                                continue
                        else:
                            compiled = src
                        compiled = self._rewrite_imports_to_generated(compiled)
                        compiled = generated_decl + compiled
                        self._write(view_path, compiled, overwrite)

                # ---------- CONTROLLER ----------
                if ctrl_mod_cfg:
                    ctrl_basename = ctrl_mod_cfg.split(".")[-1]
                    src = self._read_source(ctrl_mod_cfg)
                    ctrl_path = self.dirs["controller"] / f"{ctrl_basename}.py"
                    if src:
                        blueprint_var = self._detect_blueprint_var(src)
                        if ("{{" in src) or ("{%" in src):
                            try:
                                compiled = self.compiler.compile(src, {}, blueprint_var, entry)
                            except Exception as e:
                                _log(f"Template compilation error for controller {ctrl_mod_cfg}: {e}", lvl="ERROR")
                                continue
                        else:
                            compiled = src
                        compiled = self._rewrite_imports_to_generated(compiled)
                        compiled = generated_decl + compiled
                        self._write(ctrl_path, compiled, overwrite)
                    else:
                        # fallback controller skeleton
                        clsname = f"{ctrl_basename.capitalize()}Controller" if ctrl_basename else "GeneratedController"
                        content = (
                            "from controller.base.main import BaseController\n\n"
                            f"class {clsname}(BaseController):\n"
                            "    _method_map = {}\n    _model = None\n\n"
                            "    def handle(self, *a, **k):\n"
                            "        raise NotImplementedError\n"
                        )
                        content = self._rewrite_imports_to_generated(content)
                        content = generated_decl + content
                        self._write(ctrl_path, content, overwrite)

                # ---------- MODEL ----------
                if mdl_mod_cfg:
                    mdl_basename = mdl_mod_cfg.split(".")[-1]
                    src = self._read_source(mdl_mod_cfg)
                    mdl_path = self.dirs["model"] / f"{mdl_basename}.py"
                    if src:
                        blueprint_var = self._detect_blueprint_var(src)
                        if ("{{" in src) or ("{%" in src):
                            try:
                                compiled = self.compiler.compile(src, {}, blueprint_var, entry)
                            except Exception as e:
                                _log(f"Template compilation error for model {mdl_mod_cfg}: {e}", lvl="ERROR")
                                continue
                        else:
                            compiled = src
                        compiled = self._rewrite_imports_to_generated(compiled)
                        compiled = generated_decl + compiled
                        self._write(mdl_path, compiled, overwrite)
                    else:
                        # fallback model skeleton
                        clsname = f"{mdl_basename.capitalize()}Model" if mdl_basename else "GeneratedModel"
                        content = (
                            "from model.base.main import BaseModel\n\n"
                            f"class {clsname}(BaseModel):\n"
                            "    pass\n"
                        )
                        content = self._rewrite_imports_to_generated(content)
                        content = generated_decl + content
                        self._write(mdl_path, content, overwrite)

            except Exception as e:
                import traceback
                _log(f"Error generating {entry.get('blueprint','?')}: {e}\n{traceback.format_exc()}", lvl="ERROR")

        return True
